// Mock company data with real websites for enrichment
export const mockCompanies = [
  {
    id: 1,
    name: 'Stripe',
    description: 'Financial infrastructure platform for the internet',
    industry: 'Fintech',
    location: 'SF',
    signals: 5,
    enriched: false,
    founded: 2010,
    website: 'https://stripe.com',
    employees: 8000,
  },
  {
    id: 2,
    name: 'Notion',
    description: 'All-in-one workspace for notes, docs, and collaboration',
    industry: 'SaaS',
    location: 'SF',
    signals: 4,
    enriched: false,
    founded: 2016,
    website: 'https://notion.so',
    employees: 500,
  },
  {
    id: 3,
    name: 'Anthropic',
    description: 'AI safety company building reliable AI systems',
    industry: 'AI/ML',
    location: 'SF',
    signals: 7,
    enriched: false,
    founded: 2021,
    website: 'https://anthropic.com',
    employees: 500,
  },
  {
    id: 4,
    name: 'Figma',
    description: 'Collaborative interface design tool',
    industry: 'SaaS',
    location: 'SF',
    signals: 6,
    enriched: false,
    founded: 2012,
    website: 'https://figma.com',
    employees: 1000,
  },
  {
    id: 5,
    name: 'Vercel',
    description: 'Frontend cloud platform for developers',
    industry: 'SaaS',
    location: 'SF',
    signals: 5,
    enriched: false,
    founded: 2015,
    website: 'https://vercel.com',
    employees: 500,
  },
  {
    id: 6,
    name: 'Linear',
    description: 'Modern issue tracking and project management',
    industry: 'SaaS',
    location: 'SF',
    signals: 4,
    enriched: false,
    founded: 2019,
    website: 'https://linear.app',
    employees: 100,
  },
  {
    id: 7,
    name: 'Supabase',
    description: 'Open source Firebase alternative with Postgres',
    industry: 'SaaS',
    location: 'SF',
    signals: 5,
    enriched: false,
    founded: 2020,
    website: 'https://supabase.com',
    employees: 150,
  },
  {
    id: 8,
    name: 'Retool',
    description: 'Low-code platform for building internal tools',
    industry: 'SaaS',
    location: 'SF',
    signals: 4,
    enriched: false,
    founded: 2017,
    website: 'https://retool.com',
    employees: 400,
  },
  {
    id: 9,
    name: 'Loom',
    description: 'Video messaging for async work communication',
    industry: 'SaaS',
    location: 'SF',
    signals: 3,
    enriched: false,
    founded: 2015,
    website: 'https://loom.com',
    employees: 300,
  },
  {
    id: 10,
    name: 'Plaid',
    description: 'Financial data connectivity platform',
    industry: 'Fintech',
    location: 'SF',
    signals: 5,
    enriched: false,
    founded: 2013,
    website: 'https://plaid.com',
    employees: 1000,
  },
  {
    id: 11,
    name: 'Airtable',
    description: 'Low-code platform for building collaborative apps',
    industry: 'SaaS',
    location: 'SF',
    signals: 4,
    enriched: false,
    founded: 2012,
    website: 'https://airtable.com',
    employees: 1000,
  },
  {
    id: 12,
    name: 'Webflow',
    description: 'Visual web development platform',
    industry: 'SaaS',
    location: 'SF',
    signals: 5,
    enriched: false,
    founded: 2013,
    website: 'https://webflow.com',
    employees: 600,
  },
];

// Get unique industries for filters
export const industries = [...new Set(mockCompanies.map(c => c.industry))];

// Get unique locations for filters
export const locations = [...new Set(mockCompanies.map(c => c.location))];
